### ISSUE TITLE
<@{player_turn}> / <@{self.player_xxxx}> as an actual mention?

### ISSUE THREAD

**Issue by Skyridr** [WildStriker/WildCogs#7]
Is it possible that 

```py
        # Chess variants
        if self._board.is_variant_loss():
            return True, f"<@{self.player_black_id}> wins!"

        if self._board.is_variant_win():
            return True, f"<@{self.player_white_id}> wins!"

        # Checkmate.
        if self._board.is_checkmate():
            return True, f"Checkmate! <@{player_turn}> Wins!"

        # Stalemate.
        if self._board.is_stalemate():
            return True, "Draw by stalemate!\n" \
                f"<@{player_next.id}> has no moves!"

        if self._board.is_check():
            return False, f"<@{player_next}> you are in check. Your move is next."

        return False, f"<@{player_next}> you're up next!"
```
Can return an actual player mention? I could alter the code, but maybe an official way would be better. As embed forms can't mention users, it would be nice to be mentioned if won/lost and or if it's your turn.

So ti would look something like:

```
@ USER
EMBED FORM HERE
```

**Comment by WildStriker** [comment]
Hello,

I have implemented some changes to start, move, and draw byagreement to add an @mention above the embed to allow for proper notifications.

Looks good now, closing this issue.  Thanks for pointing this out totally missed this!
